### ISSUE TITLE
Could you please provide the final saliency maps of your model?

### ISSUE THREAD

**Issue by Karry-Wu** [liuyi1989/TCGNet#1]
Hi, congratulations on your contribution. Could you please provide the final saliency maps of your model?

**Comment by liuyi1989** [comment]
Thank you for your attention. Saliency map can be found in the following link.

通过百度网盘分享的文件：results
链接：https://pan.baidu.com/s/17rX2sm4N18hudgarXOHctA?pwd=369E 
提取码：369E 
复制这段内容打开「百度网盘APP 即可获取」
